export const siteConfig = {
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://codexpet.top",
  title: "Awesome Codex Pet",
  altNames: [
    "Codex Pet Gallery",
    "Codex 宠物画廊",
    "Codex 精品宠物",
    "Codex 小宠物",
    "Codex Pets Community",
  ],
  description:
    "Awesome Codex Pet is a curated community gallery of custom OpenAI Codex pets. Preview V1/V2 animations and install anime, game, mascot, and desktop companions.",
  descriptionZh:
    "Awesome Codex Pet 是精选的社区 Codex 宠物画廊，可预览 V1、V2 完整动画，浏览动漫、游戏、吉祥物与桌面伙伴，并在 macOS、Linux 或 Windows 上一键安装。",
  shortDescription:
    "A curated community gallery of custom OpenAI Codex pets with full animation previews and one-step installation.",
  shortDescriptionZh:
    "精选的 OpenAI Codex 宠物画廊，提供完整动作预览与一键安装。",
  ogImage: "/assets/cover/awesome-codex-pet-cover.png",
  ogImageWidth: 1659,
  ogImageHeight: 948,
  repo: "https://github.com/legeling/awesome-codex-pet",
  catalog: "/pets.json",
  collectionsCatalog: "/collections.json",
  keywords: [
    "Codex",
    "Codex pet",
    "Codex pets",
    "custom Codex pet",
    "Codex custom pets",
    "install Codex pet",
    "how to install Codex pet",
    "Codex pet gallery",
    "Codex pets gallery",
    "Codex pets library",
    "Codex pet download",
    "Codex pet share",
    "Codex pet skill",
    "Codex Hatch Pet",
    "Hatch Pet skill",
    "create Codex pet",
    "Codex pet not showing",
    "Codex /pet not working",
    "Codex pet V1",
    "Codex pet V2",
    "Codex desktop companion",
    "Codex CLI",
    "OpenAI Codex",
    "desktop pet",
    "pixel art pet",
    "anime Codex pet",
    "game character Codex pet",
    "spritesheet",
    "Codex 宠物",
    "Codex 小宠物",
    "Codex 精品宠物",
    "Codex 宠物网站",
    "Codex 宠物社区",
    "Codex 宠物市场",
    "Codex 宠物下载",
    "Codex 宠物安装",
    "Codex 宠物制作",
    "Codex 宠物自定义",
    "Codex 小宠物制作",
    "Codex 宠物不显示",
    "Codex 宠物有什么用",
    "Codex 宠物功能",
    "Codex 宠物 skill",
    "ChatGPT 桌面宠物",
    "动漫桌面宠物",
    "代码助手宠物",
    "open source pet",
    "Awesome Codex Pet",
  ],
};

export type SiteConfig = typeof siteConfig;
